#!/bin/sh

symbol() {
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
then
  # off
  echo ""
else
  if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
  then
	  # on, not connected
	  echo ""
  else
	  # on, connected
	  echo ""
  fi
fi
}

# TODO: write the code for this
name() {
echo ""
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
