* dotfiles

- *distro*: nixos
- *wm*: awesomewm
- *dm*: lightdm
- *compositor*: picom
- *bar*: polybar
- *$EDITOR*: emacs(client), vim
- *terminal*: alacritty
- *shell*: zsh + oh-my-zsh
- *launcher*: rofi
- *browser*: firefox

alongside:
- pywal for synchronizing themes through emacs' theme-magic
- miscellaneous sh scripts, wallpapers

My setups also utilize a handful of tools, such as firefox, where the configs just
aren't included. My emacs files are split up into an init.el and a src/ directory,
in which are a small handful of elisp files that init.el loads on startup.

Wallpapers I collect over time, so note that they aren't mine/I didn't make them. I've
tried to collect their sources in a sources.txt over time, but it'll likely be somewhat
of a mess at any given time.

*** nix
- canary: my desktop---dev env + steam/lutris, wifi/bluetooth, nvidia
- songbird: my laptop---dev env + steam, wifi/bluetooth, power management, amdgpu

configuration.nix should be manually changed to import etiher canary.nix or songbird.nix
based on the machine.

#+BEGIN_COMMENT
TODO:   warpd,
	    .editorconfig?
#+END_COMMENT
