* dotfiles

- *distro*: nixos
- *wm*: awesomewm, exwm
- *dm*: lightdm
- *compositor*: picom
- *bar*: polybar
- *$EDITOR*: emacs, emacsclient, vim
- *terminal*: alacritty
- *shell*: zsh + oh-my-zsh
- *launcher*: rofi, emacs' counsel
- *browser*: firefox

alongside:
- pywal for synchronizing themes through emacs' theme-magic
- miscellaneous sh scripts, wallpapers

My setups also utilize a handful of tools, such as firefox, where the configs just
aren't included. My emacs files are split up into an init.el and a src/ directory,
in which are a small handful of elisp files that init.el loads on startup.

Wallpapers I collect over time, so note that they aren't mine/I didn't make them. I've
tried to collect their sources in a sources.txt over time, but it'll likely be somewhat
of a mess at any given time.

*** nix

- canary: my desktop---awesomewm, znver3 tunings
- songbird: my laptop---exwm + extra power management stuff, znver1 tunings

configuration.nix should be manually changed to import either canary.nix or songbird.nix
based on the machine.

*** non-packaged dependencies

- https://github.com/nickclyde/rofi-bluetooth
- https://github.com/P3rf/rofi-network-manager


*** notes

- polybar colors are hardcoded to cyberpunk theme---could redo and use xresources colors
  that pywal generates on emacs theme switch

#+BEGIN_COMMENT
TODO:   warpd
#+END_COMMENT
