# a docker-compose file that initializes a docker container
# hosting a gitea instance

version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.16.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - /home/Git/dotfiles/gitea/theme:/data/custom/public/css
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
